### ISSUE TITLE
Keep getting error popup despite following instructions

### ISSUE THREAD

**Issue by imanvanassum** [cmunk/utopiaintel#1]
Hi Munk,

I'm playing around with the new intel option for my own kingdom's use.
Unfortunately I'm having a tough time fully translating the PHP example to Python/Django which I'm using for our endpoint.
I'm almost there I think, at first I was getting a popup with ERROR because I wasn't sending any response at all.
Then I figured out how to send the JSON response, and if I look at Firefox's console everything looks in order, but I'm still getting a popup that reads "Something is wrong with your endpoint.".

Could you maybe elaborate on what it is I'm doing wrong or whether my response is missing anything?
I've tried the JSON response both with 'success' set to a boolean True as well as just "True" as text.

![image](https://user-images.githubusercontent.com/18702319/28597194-d93a5fb8-719c-11e7-8bb7-3498efd321e6.png)
![image](https://user-images.githubusercontent.com/18702319/28597210-f27518ec-719c-11e7-9ad4-c4ca5f01900d.png)

Kind regards,
Iman

PS: I'd be happy to send IP addresses or province names in a more private form, but I'm not posting that here obviously ^_^

**Comment by imanvanassum** [comment]
Current error:
![image](https://user-images.githubusercontent.com/18702319/28597317-8ac98dc6-719d-11e7-881d-acd136c39711.png)

If I rollback my last changes you can see the error I got before I fixed the Access-* headers:
![image](https://user-images.githubusercontent.com/18702319/28597400-d62d9c3a-719d-11e7-943b-b5d086412ef6.png)

**Comment by cmunk** [comment]
Can you paste the information from the javascript console in as well? Is there any error there?

This is the javascript code that seems to be error'ing on your end:

```
}).done(function (html) {
try {
    var returnedData = JSON.parse(html);
    if (returnedData['success'] != true) {
        alert('Something is wrong with your parser');
    } else {
        console.log('Sent page with success!');
    }
} catch (e) {
    alert('Something is wrong with your endpoint.');
}
});
```

So it seems that it's likely the parse'ing of the html response that throws an error. Your console might give a hint.

**Comment by imanvanassum** [comment]
Hey Munk,

You're right of course, and I had a look in the debugger of my browser.
I don't understand why returnedData is undefined though, it looks my returned HTML contains the required field?
![image](https://user-images.githubusercontent.com/18702319/28694770-bb62c3c8-732b-11e7-9be2-6d25a506a15b.png)

Kind regards,
Iman

**Comment by imanvanassum** [comment]
Never mind, I was messing it up by not encoding it properly (I was sending a Python dict instead of JSON object before fixing it).
This is the answer with Python 3.6:
```
reply = {
    'success' : True,
}
i_hate_javascript = json.JSONEncoder().encode(reply)
return HttpResponse(i_hate_javascript)
```

**Comment by cmunk** [comment]
OK glad you solved it.
